// Copyright 2026
//
// chi_rni: top-level Scheme-1 (non-coherent AXI-to-CHI) adaptor.  This is a
// thin wrapper around chi_rni_core that the customer owns.  The core exposes
// a decoded CHI channel interface; a profile shim (written for a specific
// NoC/BFM) drives the actual REQ/RSP/DAT flits and credit counters.

`include "chi_rni_defines.svh"

module chi_rni #(
    parameter int unsigned ADDR_WIDTH       = 44,
    parameter int unsigned AXI_DATA_WIDTH   = 128,
    parameter int unsigned AXI_ID_WIDTH     = 8,
    parameter int unsigned CHI_DATA_WIDTH   = 256,
    parameter int unsigned CHI_TXNID_WIDTH  = 12,
    parameter int unsigned CHI_DBID_WIDTH   = 12,
    parameter int unsigned CHI_DATAID_WIDTH = 2,
    parameter int unsigned DATAID_LAYOUT     = `CHI_RNI_DATAID_LAYOUT_IHI0050E,
    parameter int unsigned ORDER_POLICY      = `CHI_RNI_ORDER_POLICY_PERMISSIVE,
    parameter int unsigned PARENT_ENTRIES   = 32,
    parameter int unsigned MAX_AXI_BEATS    = 256,
    parameter bit          ACCESS_DEVICE    = 1'b0,
    parameter bit          FORCE_NONSECURE  = 1'b1,
    parameter logic [1:0]  ORDER_VALUE      = 2'b00,
    parameter logic [3:0]  QOS_VALUE        = 4'b0000,
    parameter bit          ENABLE_WRITE_NO_SNP_FULL = 1'b0,
    parameter logic [2:0]  FULL_LINE_SIZE_LOG2 = `CHI_RNI_MAX_CHILD_LOG2
)(
    input  logic clk,
    input  logic rst_n,
    input  logic link_active,

    // AXI read channel
    input  logic [AXI_ID_WIDTH-1:0]  s_axi_arid,
    input  logic [ADDR_WIDTH-1:0]    s_axi_araddr,
    input  logic [7:0]               s_axi_arlen,
    input  logic [2:0]               s_axi_arsize,
    input  logic [1:0]               s_axi_arburst,
    input  logic [2:0]               s_axi_arprot,
    input  logic                     s_axi_arlock,
    input  logic                     s_axi_arvalid,
    output logic                     s_axi_arready,
    output logic [AXI_ID_WIDTH-1:0]  s_axi_rid,
    output logic [AXI_DATA_WIDTH-1:0] s_axi_rdata,
    output logic [1:0]               s_axi_rresp,
    output logic                     s_axi_rlast,
    output logic                     s_axi_rvalid,
    input  logic                     s_axi_rready,

    // AXI write channel
    input  logic [AXI_ID_WIDTH-1:0]  s_axi_awid,
    input  logic [ADDR_WIDTH-1:0]    s_axi_awaddr,
    input  logic [7:0]               s_axi_awlen,
    input  logic [2:0]               s_axi_awsize,
    input  logic [1:0]               s_axi_awburst,
    input  logic [2:0]               s_axi_awprot,
    input  logic                     s_axi_awlock,
    input  logic                     s_axi_awvalid,
    output logic                     s_axi_awready,
    input  logic [AXI_DATA_WIDTH-1:0] s_axi_wdata,
    input  logic [AXI_DATA_WIDTH/8-1:0] s_axi_wstrb,
    input  logic                     s_axi_wlast,
    input  logic                     s_axi_wvalid,
    output logic                     s_axi_wready,
    output logic [AXI_ID_WIDTH-1:0]  s_axi_bid,
    output logic [1:0]               s_axi_bresp,
    output logic                     s_axi_bvalid,
    input  logic                     s_axi_bready,

    // CHI decoded channels
    output logic                    chi_txreq_valid,
    input  logic                    chi_txreq_ready,
    output logic [6:0]              chi_txreq_opcode,
    output logic [ADDR_WIDTH-1:0]   chi_txreq_addr,
    output logic [2:0]              chi_txreq_size,
    output logic [CHI_TXNID_WIDTH-1:0] chi_txreq_txnid,
    output logic                    chi_txreq_device,
    output logic                    chi_txreq_ns,
    output logic [1:0]              chi_txreq_order,
    output logic [3:0]              chi_txreq_qos,
    output logic                    chi_txreq_allow_retry,

    input  logic                    chi_rxrsp_valid,
    output logic                    chi_rxrsp_ready,
    input  logic [CHI_TXNID_WIDTH-1:0] chi_rxrsp_txnid,
    input  logic [1:0]              chi_rxrsp_kind,
    input  logic [CHI_DBID_WIDTH-1:0]  chi_rxrsp_dbid,
    input  logic [1:0]              chi_rxrsp_resp_err,

    input  logic                    chi_rxdat_valid,
    output logic                    chi_rxdat_ready,
    input  logic [CHI_TXNID_WIDTH-1:0] chi_rxdat_txnid,
    input  logic [CHI_DATAID_WIDTH-1:0] chi_rxdat_data_id,
    input  logic [CHI_DATA_WIDTH-1:0] chi_rxdat_data,
    input  logic [1:0]              chi_rxdat_resp_err,

    output logic                    chi_txdat_valid,
    input  logic                    chi_txdat_ready,
    output logic [CHI_TXNID_WIDTH-1:0] chi_txdat_txnid,
    output logic [CHI_DBID_WIDTH-1:0]  chi_txdat_dbid,
    output logic [CHI_DATA_WIDTH-1:0]  chi_txdat_data,
    output logic [CHI_DATA_WIDTH/8-1:0] chi_txdat_be,
    output logic [CHI_DATAID_WIDTH-1:0] chi_txdat_data_id,
    output logic                    chi_txdat_last,

    output logic                    protocol_error
);

  chi_rni_core #(
      .ADDR_WIDTH        (ADDR_WIDTH),
      .AXI_DATA_WIDTH    (AXI_DATA_WIDTH),
      .AXI_ID_WIDTH      (AXI_ID_WIDTH),
      .CHI_DATA_WIDTH    (CHI_DATA_WIDTH),
      .CHI_TXNID_WIDTH   (CHI_TXNID_WIDTH),
      .CHI_DBID_WIDTH    (CHI_DBID_WIDTH),
      .CHI_DATAID_WIDTH  (CHI_DATAID_WIDTH),
      .DATAID_LAYOUT     (DATAID_LAYOUT),
      .ORDER_POLICY      (ORDER_POLICY),
      .PARENT_ENTRIES    (PARENT_ENTRIES),
      .MAX_AXI_BEATS     (MAX_AXI_BEATS),
      .ACCESS_DEVICE     (ACCESS_DEVICE),
      .FORCE_NONSECURE   (FORCE_NONSECURE),
      .ORDER_VALUE       (ORDER_VALUE),
      .QOS_VALUE         (QOS_VALUE),
      .ENABLE_WRITE_NO_SNP_FULL (ENABLE_WRITE_NO_SNP_FULL),
      .FULL_LINE_SIZE_LOG2 (FULL_LINE_SIZE_LOG2)
  ) u_core (
      .clk               (clk),
      .rst_n             (rst_n),
      .link_active       (link_active),
      .s_axi_arid        (s_axi_arid),
      .s_axi_araddr      (s_axi_araddr),
      .s_axi_arlen       (s_axi_arlen),
      .s_axi_arsize      (s_axi_arsize),
      .s_axi_arburst     (s_axi_arburst),
      .s_axi_arprot      (s_axi_arprot),
      .s_axi_arlock      (s_axi_arlock),
      .s_axi_arvalid     (s_axi_arvalid),
      .s_axi_arready     (s_axi_arready),
      .s_axi_rid         (s_axi_rid),
      .s_axi_rdata       (s_axi_rdata),
      .s_axi_rresp       (s_axi_rresp),
      .s_axi_rlast       (s_axi_rlast),
      .s_axi_rvalid      (s_axi_rvalid),
      .s_axi_rready      (s_axi_rready),
      .s_axi_awid        (s_axi_awid),
      .s_axi_awaddr      (s_axi_awaddr),
      .s_axi_awlen       (s_axi_awlen),
      .s_axi_awsize      (s_axi_awsize),
      .s_axi_awburst     (s_axi_awburst),
      .s_axi_awprot      (s_axi_awprot),
      .s_axi_awlock      (s_axi_awlock),
      .s_axi_awvalid     (s_axi_awvalid),
      .s_axi_awready     (s_axi_awready),
      .s_axi_wdata       (s_axi_wdata),
      .s_axi_wstrb       (s_axi_wstrb),
      .s_axi_wlast       (s_axi_wlast),
      .s_axi_wvalid      (s_axi_wvalid),
      .s_axi_wready      (s_axi_wready),
      .s_axi_bid         (s_axi_bid),
      .s_axi_bresp       (s_axi_bresp),
      .s_axi_bvalid      (s_axi_bvalid),
      .s_axi_bready      (s_axi_bready),
      .chi_txreq_valid   (chi_txreq_valid),
      .chi_txreq_ready   (chi_txreq_ready),
      .chi_txreq_opcode  (chi_txreq_opcode),
      .chi_txreq_addr    (chi_txreq_addr),
      .chi_txreq_size    (chi_txreq_size),
      .chi_txreq_txnid   (chi_txreq_txnid),
      .chi_txreq_device  (chi_txreq_device),
      .chi_txreq_ns      (chi_txreq_ns),
      .chi_txreq_order   (chi_txreq_order),
      .chi_txreq_qos     (chi_txreq_qos),
      .chi_txreq_allow_retry (chi_txreq_allow_retry),
      .chi_rxrsp_valid   (chi_rxrsp_valid),
      .chi_rxrsp_ready   (chi_rxrsp_ready),
      .chi_rxrsp_txnid   (chi_rxrsp_txnid),
      .chi_rxrsp_kind    (chi_rxrsp_kind),
      .chi_rxrsp_dbid    (chi_rxrsp_dbid),
      .chi_rxrsp_resp_err(chi_rxrsp_resp_err),
      .chi_rxdat_valid   (chi_rxdat_valid),
      .chi_rxdat_ready   (chi_rxdat_ready),
      .chi_rxdat_txnid   (chi_rxdat_txnid),
      .chi_rxdat_data_id (chi_rxdat_data_id),
      .chi_rxdat_data    (chi_rxdat_data),
      .chi_rxdat_resp_err(chi_rxdat_resp_err),
      .chi_txdat_valid   (chi_txdat_valid),
      .chi_txdat_ready   (chi_txdat_ready),
      .chi_txdat_txnid   (chi_txdat_txnid),
      .chi_txdat_dbid    (chi_txdat_dbid),
      .chi_txdat_data    (chi_txdat_data),
      .chi_txdat_be      (chi_txdat_be),
      .chi_txdat_data_id (chi_txdat_data_id),
      .chi_txdat_last    (chi_txdat_last),
      .protocol_error    (protocol_error)
  );

endmodule
